// <auto-generated />
namespace VDMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testfinal01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testfinal01));
        
        string IMigrationMetadata.Id
        {
            get { return "202103300726165_testfinal01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
